create program ice-cream-shop
AnzhelikaAlexandrovna/HTMLAcademy pull request #5
Opened 2023-05-06 21:39 UTC by AnzhelikaAlexandrovna

2023-05-17 16:36 UTC, ProMastersss requested changes

2023-05-17 16:36 UTC, ProMastersss commented on js-browser/ice-cream-shop(2)/script.js
> +    price.textContent += '₽/кг';
Можно заменить на одну строчку
`const price = makeElement('p', 'good__price', product.price + '₽/кг')`

2023-05-17 16:47 UTC, AnzhelikaAlexandrovna commented on js-browser/ice-cream-shop(2)/script.js
> +    price.textContent += '₽/кг';
Та ты же сам мне говорил, что нельзя объект сконкатенировать со строкой. Или я чего-то не понимаю

2023-05-18 06:50 UTC, ProMastersss approved these changes
Мержи оба запроса в Pull requests
<img width="342" alt="image" src="https://github.com/AnzhelikaAlexandrovna/HTMLAcademy/assets/14785485/d726c542-d607-47fd-b18e-734d2c33f6fb">

2023-05-18 06:50 UTC, ProMastersss commented on js-browser/ice-cream-shop(2)/script.js
> +    price.textContent += '₽/кг';
product - объект
product.price - это число

У тебя было, что функция возвращает объект и с объектом ты складывала
60 строка
![telegram-cloud-photo-size-2-5413481212464449159-y](https://github.com/AnzhelikaAlexandrovna/HTMLAcademy/assets/14785485/cd1e300f-1974-4604-95f5-1e078071ef03)

2023-05-19 06:51 UTC, merged